version: "3.1"
services:
    werbserver:
      build: .
      ports:
      - "8001:80"
      volumes:
        - ./:/var/www/html/
      links:
        - mysql
      networks:
        - default

    mysql:
      image: mysql:5.6
      ports:
        - "3306:3306"
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: barbearia22
        MYSQL_USER: vinicius
        MYSQL_PASSWORD: senhadificil
        MYSQL_ROOT_PASSWORD: passworddificil
        
      volumes:
        - ./mysql:/docker-entrypoint-initdb.d
        - ./mysql/config/:/etc/mysql/conf.d
        
      networks:
        - default

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - mysql:mysql
      ports:
        - 8000:80
      environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: senhadificil
        MYSQL_ROOT_PASSWORD: root
        volumes:

   